Update documentation for removing manuals/sections
alphagov/hmrc-manuals-api pull request #903
Opened 2024-01-17 14:49 UTC by brucebolt

It was not clear to Tech 2nd Line how to determine the `manual-slug` and `section-slug` for a section, therefore making the instructions clearer.

This application is owned by the publishing platform team. Please let us know in #govuk-publishing-platform when you raise any PRs.

⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️

2024-01-17 15:31 UTC, jkempster34 requested changes
Hi, thanks for doing this.

I've not run these before so I might be a good candidate to suggest changes.

Could we at least make sure the slugs in the arguments are different `manual-slug,manual-slug-1` instead of how they are currently (`manual-slug,manual-slug`)

I also wonder if this would be clearer if it was even more wordy, so I've added some suggestions there too

2024-01-17 15:31 UTC, jkempster34 commented on docs/extended_documentation.md
> +To completely remove a manual and all of its sections (removal means replacing the published manual with a 410 Gone response):
Do the sections 410 as well? Could this be `removal means replacing the published manual and sections with 410 Gone responses`

2024-01-17 15:31 UTC, jkempster34 commented on docs/extended_documentation.md
> +> The slugs can be determined from the URL:
Very clear!

2024-01-17 15:31 UTC, jkempster34 commented on docs/extended_documentation.md
> +rake 'remove_hmrc_manuals[manual-slug,manual-slug]'
Can this be:

---

To completely remove a manual and all of its sections, run the `remove_hmrc_manuals` task with the slugs of the manuals you wish to remove. Removal means replacing the published manual and sections with 410 Gone responses. For example:

`rake 'remove_hmrc_manuals[manual-slug,manual-slug-2]'`

2024-01-17 15:31 UTC, jkempster34 commented on docs/extended_documentation.md
> +To redirect a section back to the parent manual:
Can this be (something like):

To redirect a section back to the parent manual, run the `redirect_hmrc_section_to_parent_manual` task with the slug of the manual you want to redirect the sections to, followed by the slugs of the sections. For example:

rake 'redirect_hmrc_section_to_parent_manual[manual-slug,section-slug,section-slug-2]'

2024-01-17 15:31 UTC, jkempster34 commented on docs/extended_documentation.md
> +To remove the section (removal means replacing the published manual with a 410 Gone response):
Can this be:

To completely remove a section, run the `remove_hmrc_sections` task with the slugs of the sections you wish to remove. Removal means replacing the published sections with 410 Gone responses. For example:

rake 'remove_hmrc_sections[section-slug,section-slug-2]'

2024-01-18 08:03 UTC, brucebolt commented on docs/extended_documentation.md
> +To completely remove a manual and all of its sections (removal means replacing the published manual with a 410 Gone response):
Yes, the sections are also removed.  Will update to your suggested wording.

2024-01-18 08:11 UTC, brucebolt commented
Thanks @jkempster34 for the great suggestions!  I've updated the docs and given multiple examples where a task can be use with a single or multiple arguments.

2024-01-18 09:04 UTC, jkempster34 approved these changes
💯

2024-01-18 09:11 UTC, merged